export const ADD_KEYWORD = "ADD_KEYWORD";
export const ADD_SERIAL_RESPONSE = "ADD_SERIAL_RESPONSE";
export const ADD_UART_DEVICE = "ADD_UART_DEVICE";
export const ACTION_ClEAR_LOGS = "ACTION_ClEAR_LOGS";
export const CHANGE_UART_DEVICE_STATE = "CHANGE_UART_DEVICE_STATE";